

a=['5-alpha-androst-16-one','5-alpha-androst-16-en-3alpha-ol','geranyl acetone','geranyl acetate','PMD','Icaridin','permethrin','linalool oxide','delta-decalactone','Nepetalactone','gamma-decalactone','(-)-carvone',' ','DEET','DEPA','cuminyl alcohol',' ','(1S,4R)-(-)-fenchone','1-dodecanol','1-chlorododecane','Geraniol','(1R)-(-)-fenchone','hexadecanoic acid','Eucalyptol','(+)-fenchone','carvacrol','tetradecanoic acid','(±)-β-Citronellol','Citronellal','limonene','tridecanoic acid','phenethyl acetate','IR3535','decanal','dodecanoic acid','2-propylphenol','benzyl acetate','methyl-2-methyl benzoate','acetophenone','2-phenoxy ethanol','2-nonanone','3-methylindole','4-methylcyclohexanol','methyl salicylate','1-octen-3-ol','2-ethyl-1-hexanol','6-methylhept-5-en-2-one','decanoic acid','4-ethylphenol','nonanal','2-ethylphenol','methyl benzoate','methyl caprylate','2-ethyl toluene','2-acetylpyridine','3-methyl-2-cyclohexen-1-ol','2-acetylthiophene','7-octenoic acid','3-octanone','octanal','cyclohexanone','indole','benzaldehyde','3-methylphenol','4-methylphenol','ethyl hexanoate','2-iso-butyl-thiazole','1-hepten-3-ol','nonanoic acid','2-heptanone','isoamyl acetate','2-methylphenol','2-acetylthiazole','2,4,5-trimethyl thiazole','amyl acetate','heptanal','Z2-hexenol','octanoic acid','E2-hexenol','3-methyl-2-hexenoic acid','phenol','1-hexen-3-ol','cis-3-hexen-1-ol','isobutyl acetate','octadecanoic acid','1-hexanol','heptanoic acid','cadaverine','E2-hexenal','ethyl butyrate','hexanal','heptane','3-methyl-1-butanol','2-oxopentanoic acid','4,5-dimethyl thiazole','L(+) lactic acid','cadaverine','2-oxohexanoic acid','2-ethoxythiazole','1-pentanol','propyl acetate','hexanoic acid','2,3-butanedione','ethyl propanoate','putrescine','2-oxobutanoic acid','4-methylthiazole','2-butanone','methyl propanoate','isovaleric acid','1-butanol','ethyl acetate','pentanoic acid','isobutyric acid','ammonia','acetone','octadecanoic acid','2-oxopropanoic acid','ethyl formate','thiazole','butanoic acid','acetic acid','ethanol','propanoic acid','dimethylsulfide','methanol']

b=['Decanal','1-Octen-3-ol','Indole','N,N-diethyl-m-toluamide (DEET)','7-Octenoic acid','(Z)-3-Hexenol','Geranylacetone','1-Octanol','Linalool','Octanal','1-Dodecanol','(E)-2-Hexenal','Jasmone','1-Decanol','6-Methyl-5-hepten-2-one','1-Nonanol','Hexanal','Benzaldehyde','Menthol','Nonanal','(-)-citronellal','(E)-2-Octenal','(E)-2-Nonenal']

c=['amyl acetate', '(1s,4r)-(-)-fenchone', '2-oxobutanoic acid', 'ammonia', '5-alpha-androst-16-one', 'cis-3-hexen-1-ol', '3-methyl-1-butanol', '2-acetylthiophene', '1-pentanol', 'eucalyptol', '3-methyl-2-hexenoic acid', 'acetic acid', 'acetone', '2-iso-butyl-thiazole', 'methyl propanoate', '1-hexanol', 'propyl acetate', '2-oxopropanoic acid', 'gamma-decalactone', 'pmd', 'putrescine', 'phenethyl acetate', '2-heptanone', 'nepetalactone', '1-hepten-3-ol', '2-propylphenol', '4-methylthiazole', 'butanoic acid', 'isobutyric acid', 'dimethylsulfide', '2-ethyl-1-hexanol', '(1r)-(-)-fenchone', 'hexanoic acid', '(\xc2\xb1)-\\u03b2-citronellol', '5-alpha-androst-16-en-3alpha-ol', 'isobutyl acetate', '(+)-carvone', '2-oxohexanoic acid', '2-nonanone', 'ethanol', '(+)-fenchone', 'methyl salicylate', 'isoamyl acetate', 'cuminyl alcohol', 'delta-decalactone', '2-methylphenol', 'acetophenone', '(-)-carvone', '2-acetylthiazole', 'methyl caprylate', '2-ethylphenol', 'decanoic acid', 'propanoic acid', 'ethyl butyrate', '3-octanone', 'ethyl propanoate', 'e2-hexenol', 'heptane', '4-ethylphenol', 'ethyl acetate', '3-methylphenol', '2,4,5-trimethyl thiazole', 'ir3535', 'thiazole', 'carvacrol', '4,5-dimethyl thiazole', '4-methylcyclohexanol', '2-ethyl toluene', 'depa', 'linalool oxide', 'cyclohexanone', 'permethrin', '2-butanone', 'deet', 'z2-hexenol', 'heptanal', '2-phenoxy ethanol', 'l(+) lactic acid', 'cadaverine', '1-hexen-3-ol', 'ethyl formate', 'geraniol', '2-oxopentanoic acid', 'isovaleric acid', 'tetradecanoic acid', 'methanol', 'phenol', '2,3-butanedione', '4-methylphenol', 'limonene', '1-chlorododecane', '1-butanol', 'eucamalol', '2-acetylpyridine', '2-ethoxythiazole', 'benzyl acetate', '3-methylindole', '3-methyl-2-cyclohexen-1-ol', '(e)-2-octenal', '(z)-3-hexenol', '3,7-dimethyloctanol', 'benzoates', 'aromatic compounds', 'others', 'jasmone', '3,7-dimethyloctyl benzoate', '2-phenylethyl benzoate', 'carboxylic acids', '1-octanol', '1-nonanol', '4-hydroxy-4\\u2019-isopropylazobenzene', 'undecanoic acid', '(e)-b-farnesene', 'p-tert-butyl benzaldehyde', 'p-tert-butylbenzophenone', 'a-pentylcinnamyl alcohol', 'p-tert-butylphenyl benzoate', '1-decanol', '(e)-2-nonenal', 'linalool', 'benzyl benzoate', 'phenyl benzoate', 'butyl p-nitrobenzoate', 'n-p-isopropylphenyl-p-', 'retinal', 'p-tolyl benzoate', 'butyl cinnamate', 'butyl p-tert-butylbenzoate', 'p-isopropylphenyl benzoate', 'methyl cinnamate', 'n,n-diethyl-m-toluamide (deet)', 'phenylbenzylhydrazine', 'm-cresol', 'o-hydroxybenzaldehyde', '3,7-dimethyloctyl acetate', 'retinol', 'hydroxybenzimine', 'isobutyl p-nitrobenzoate', 'farnesol', 'a-pentyl cinnamaldehyde', 'aldehydes and ketones', '2-pyrrolyl-p-methyl-azobenzene', '3-hexyl benzoate', 'p-cresol', 'menthol']

a = [i.lower() for i in a]
b = [i.lower() for i in b]

for i in c:
	try:
		a.remove(i)
	except ValueError:
		pass

	try:
		b.remove(i)
	except ValueError:
		pass

print "MOOMOOMOO".join(a)
print "\n"
print "MOOMOOMOO".join(b)